import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";

import { greenTheme } from "@/theme/Theme";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={greenTheme}>
        <CssBaseline />
        <body className={`h-screen ${inter.className}`}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
